### ISSUE TITLE
install-extra-packages Fails

### ISSUE THREAD

**Issue by thesupremecommander** [KnightSwarm/Minstall#47]
Running the `install-extra-packages` module fails with:

```
E: Unable to locate package 0
```

I would suspect an error in parsing a package list somewhere.

**Comment by maxexcloo** [comment]
Will look into it.

**Comment by maxexcloo** [comment]
The issue is that, by default Minstall doesn't contain any module configuration in config.ini, it must first be populated by running the minstall -s command. This runs through the config.ini files for each module and appends them to the main configuration file.
When 3.0 ships I'll ensure that the default configuration is populated.

**Comment by thesupremecommander** [comment]
Ah, makes sense. You might want to make the module fail if the function that reads the config returns 0, then, just to avoid confusion.

**Comment by maxexcloo** [comment]
Noted!
