### ISSUE TITLE
Debian 7 x86_64 BS

### ISSUE THREAD

**Issue by maxexcloo** [KnightSwarm/Minstall#61]
This is just ridiculously broken on a level I've never seen before, it works flawlessly in 32 bit, why doesn't it work in 64 bit?!

**Comment by thesupremecommander** [comment]
I encountered this issue while trying to set up a VPS of mine... at least I'm assuming so because I couldn't get clean-packages to work.

I think that the issue is caused because dpkg cannot tell whether to keep i386 or amd64 packages when given just the base package name. Appending the architecture seemed to solve the problem for at least one package.

Therefore, if you can figure out which packages you want on amd64, i386, or both, it's trivial to fix the issue. I'll probably submit a pull which keeps both architectures of ambiguous packages to resolve the problem safely until you can figure out what exactly you want to keep.

**Comment by thesupremecommander** [comment]
Well, I just realized that the package list is shared by both architectures, so it won't work to embed amd64 packages in the file.

That leaves a few options: for one, the quick and dirty option is to remove all of the i386 packages before install, allowing dpkg to only install amd64 packages, done via a command (sourced from [an Ask Ubuntu answer](http://askubuntu.com/a/151178)) like:

```
sudo apt-get remove `dpkg --get-selections | grep i386 | awk '{print $1}'`
```

The other and probably better long-term option is to maintain separate package lists and have the module automatically determine which one to install based on the architecture, as it does if the server is hardware-based already. This has the advantage of allowing individual i386 packages to be kept if necessary.
